# Generated by Django 5.0.4 on 2024-05-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='image',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
    ]
