# Generated by Django 5.0.4 on 2024-05-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_medicalrecord_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='view',
            field=models.CharField(default='', max_length=5),
        ),
    ]
