# Generated by Django 5.0.4 on 2024-04-18 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(default='2000-01-01')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('ssn', models.CharField(default='', max_length=9)),
                ('password', models.CharField(default='', max_length=128)),
                ('doctor_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('specialty', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='medical_records'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='ssn',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='medical.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical.doctor'),
            preserve_default=False,
        ),
    ]
