# Generated by Django 5.0.4 on 2024-04-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(default='Oncologist', max_length=50),
        ),
    ]
