# Generated by Django 5.0.4 on 2024-04-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_medicalrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
